import abc
from bs4 import BeautifulSoup
from selenium import webdriver
import requests
import json


class Scraper(abc.ABC):
    """Abstract class used to represent a custom web scraper."""

    def __init__(self, url: str) -> None:
        """
        :param url: url to scrape
        """
        self.url: str = url
        self._make_soup()
        self.result = None

    @abc.abstractmethod
    def scrape(self) -> None:
        """
        Scrape website to collect data.
        :return: None
        """
        pass

    def _make_soup(self, html=None) -> None:
        """
        Make BS4's soup.
        :param html: html generated by Selenium.
        """
        if not html:
            # BS4
            req = requests.get(self.url)
            html = req.content
        self._soup: BeautifulSoup = BeautifulSoup(html, "html.parser")

    def _get_selenium_driver(self) -> None:
        self._driver = webdriver.Chrome()
        self._driver.get(self.url)

    def save_data_to_json(self, data, filename='data.json'):
        with open(filename, 'w') as file:
            json.dump(data, file)
